# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('private', 'private'), ('published', 'published'), ('adopted', 'adopted')], default='private', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(max_length=40)),
                ('photo', models.ImageField(blank=True, upload_to='dogs/media')),
                ('description', models.TextField(blank=True, help_text='Additional information about this goat.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this goat.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
